services:
  openwebui:
    build: 
      context: ./custom_open
      dockerfile: Dockerfile.openwebui
      args:
        OPENAI_API_BASE_URLS: ${OPENAI_API_BASE_URLS}
    container_name: openwebui_custom
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
      - ./shared_output:/app/output            
    env_file:
      - ./custom_open/.env
    restart: always
    command: >
      sh -c "exec /app/backend/start.sh"
      
  pipelines:
    build: 
      context: ./custom_pipeline
      dockerfile: Dockerfile.pipelines
    ports:
      - "9099:9099"
    extra_hosts:
      host.docker.internal: host-gateway
    restart: always
    env_file:
      - ./custom_pipeline/.env
        
volumes:
  open-webui:
  pipelines:
