version: '3'
services:

  openwebui:
    build: 
      context: .
      dockerfile: Dockerfile.service2
    image: my-custom-openwebui
    container_name: openwebui_custom
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
       
  pipelines:
    build: 
      context: .
      dockerfile: Dockerfile.service1
    image: my-custom-pipelines
    ports:
      - "9099:9099"
    extra_hosts:
      host.docker.internal: host-gateway
    restart: always
volumes:
  open-webui:
  pipelines: