services:
  openwebui:
    build: 
      context: ./custom_open
      dockerfile: Dockerfile.openwebui
    container_name: openwebui_custom
    ports:
      - "3000:8080"
      - "5454:5454"
    volumes:
      - open-webui:/app/backend/data
      - ./shared_output:/app/output            
    env_file:
      - .env
    restart: always
    command: >
      sh -c "node src/feedback/app.js & exec /app/backend/start.sh"
      
  pipelines:
    build: 
      context: ./custom_pipeline
      dockerfile: Dockerfile.pipelines
    ports:
      - "9099:9099"
    extra_hosts:
      host.docker.internal: host-gateway
    restart: always
    env_file:
      - .env
     
volumes:
  open-webui:
  pipelines:
