services:
  openwebui:
    build: 
      context: ./custom_open
      dockerfile: Dockerfile.openwebui
    container_name: openwebui_custom
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    env_file:
          - .env

  pipelines:
    build: 
      context: ./custom_pipeline
      dockerfile: Dockerfile.pipelines
    ports:
      - "9099:9099"
    extra_hosts:
      host.docker.internal: host-gateway
    restart: always
    env_file:
          - .env
     
volumes:
  open-webui:
  pipelines:
