[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "ofer-knowledge-rag"
version = "1.0.0"
requires-python = ">=3.10"
dependencies = [
    "Flask[async] == 3.1.0",
    "certifi == 2024.12.14",
    "google-auth == 2.38.0",
    "google-cloud-storage == 3.0.0",
    "nltk == 3.9.1",
    "numpy == 1.26.4", 
    "openpyxl == 3.0.10" , 
    "pandas == 2.0.3",
    "python-dotenv == 1.0.1",
    "requests == 2.32.3",
]

[project.optional-dependencies]
test = [
  "pytest==8.3.4",
  "pytest_mock==3.14",
]
lint = [
  "ruff==0.9.6",
  "pre-commit==4.1"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = ["src"]
